### ISSUE TITLE
LCDJunoG-main.zip Failed - Virus Detected 

### ISSUE THREAD

**Issue by bhamadicharef** [dpeddi/LCDJunoG#2]
When I try to download the LCDJunoG-main.zip 
It Failed - and Windows10 say Virus Detected !

Please double check !!

**Comment by dpeddi** [comment]
Thank you for reporting. I think is a false positive, however I've updated pioasm with  pioasm.exe from tool-pioasm-rp2040-earlephilhower  repository.

**Comment by bhamadicharef** [comment]
ok now thanks
